// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU8-zNFY_WQ9OZjre5HsFg4ynUFEazXY8',
    appId: '1:237962392808:web:1a860746f4b2fb2033855d',
    messagingSenderId: '237962392808',
    projectId: 'push-notification-test-342a7',
    authDomain: 'push-notification-test-342a7.firebaseapp.com',
    storageBucket: 'push-notification-test-342a7.appspot.com',
    measurementId: 'G-6XCKMCL56J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3YLAiSXXV4yNfjanXjfYxqqfP66f7hFE',
    appId: '1:237962392808:android:9824a0de49117c3933855d',
    messagingSenderId: '237962392808',
    projectId: 'push-notification-test-342a7',
    storageBucket: 'push-notification-test-342a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwrmlGQo0hEFCgzAu_Fe6RRMr6og1rMQs',
    appId: '1:237962392808:ios:de6c74640a22783f33855d',
    messagingSenderId: '237962392808',
    projectId: 'push-notification-test-342a7',
    storageBucket: 'push-notification-test-342a7.appspot.com',
    iosBundleId: 'app.gigachad.gigachat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwrmlGQo0hEFCgzAu_Fe6RRMr6og1rMQs',
    appId: '1:237962392808:ios:34d2acb881ca51e333855d',
    messagingSenderId: '237962392808',
    projectId: 'push-notification-test-342a7',
    storageBucket: 'push-notification-test-342a7.appspot.com',
    iosBundleId: 'app.gigachad.gigachat.RunnerTests',
  );
}
